package com.haguodutimes.heatingsys.entity;

public class IndexGen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_gen.GEN_NAME
     *
     * @mbg.generated
     */
    private String genName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_gen.GEN_VALUE
     *
     * @mbg.generated
     */
    private String genValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_gen.GEN_NAME
     *
     * @return the value of index_gen.GEN_NAME
     *
     * @mbg.generated
     */
    public String getGenName() {
        return genName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_gen.GEN_NAME
     *
     * @param genName the value for index_gen.GEN_NAME
     *
     * @mbg.generated
     */
    public void setGenName(String genName) {
        this.genName = genName == null ? null : genName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_gen.GEN_VALUE
     *
     * @return the value of index_gen.GEN_VALUE
     *
     * @mbg.generated
     */
    public String getGenValue() {
        return genValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_gen.GEN_VALUE
     *
     * @param genValue the value for index_gen.GEN_VALUE
     *
     * @mbg.generated
     */
    public void setGenValue(String genValue) {
        this.genValue = genValue == null ? null : genValue.trim();
    }
}