package com.haguodutimes.heatingsys.mapper;

import com.haguodutimes.heatingsys.entity.IndexGen;

public interface IndexGenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_gen
     *
     * @mbg.generated
     */
    int insert(IndexGen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_gen
     *
     * @mbg.generated
     */
    int insertSelective(IndexGen record);
}